### PR TITLE
Added AKG, Sony and Lectrosonics equipment

### PR DESCRIPTION
**Pull request by philipdroberts**

### CODE REVIEW

**Comment by RussellAult** [comment]
Thanks for the pull request! It looks like you uploaded the same Sony profile twice, but once in a folder labelled "AKG"; was there a different profile supposed to go in there? Also, what is the file labelled "a" in the Sony folder for?

**Comment by RussellAult** [comment]
Oh, also, looking at the Info section for the Lectro gear, I really appreciate the content, but the collection as a whole here falls under a Creative Commons Attribution Share Alike license (see LICENSE.txt). Do you have permission from Lectro to share that information under this license? Thanks!

**Comment by philipdroberts** [comment]
The “a” file is an artifact, couldn’t figure out how to create a folder with out making a file in side at the same time.

I’ve uploaded the AKG file, do I need to make a new pull request?

Hadn’t really thought about licenceing so probably best not to pull the Lectro wideband files

Philip

**Comment by RussellAult** [comment]
I'm no Git expert, but I'm happy to share what I've learned:

Pull Requests relate to pulling one "Branch" into another (as opposed to specific "Commits"), so any changes you make to your Branch (like deleting that "a" file or uploading the new AKG profile) automatically become part of the existing Pull Request. This means there's no reason to make another one (since this one will track the changes you make until it's merged).

If you ever need to check, each Pull Request on GitHub as a "Files changed" tab that will show you exactly what you're changing with the Pull Request.

To that end, would you mind removing the Lectro-provided files (and editing the Info files to match)?

Thanks again for adding to the collection!

**Comment by philipdroberts** [comment]
Lectro stuff removed.

This is my first time using Git, I'm not a dev but hang out around them enough I've heard a lot about it,

**Comment by RussellAult** [comment]
Well, this is my first time _hosting_ a Git-based project, so I'm learning a lot. Anyway, this looks great, thanks for the contribution!

**Pull request merged**
